# Generated by Django 5.0.7 on 2024-07-15 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageSignedUrl',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
