# Generated by Django 5.0.7 on 2024-07-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imageSignedUrl',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.FileField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(default=None, max_length=1000),
        ),
    ]
