# Generated by Django 5.0.7 on 2024-07-18 08:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_image_imagesignedurl_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(default=None, storage=api.models.CustomS3Boto3Storage(), upload_to='images/'),
        ),
    ]
